// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore.Context;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250418145618_SeedProdutData")]
    partial class SeedProdutData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Tarih Kitabı"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Şiir Kitabı"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bilişim Kitabı"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Biyoloji Kitabı"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Felsefe Kitabı"
                        });
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Frasques d'Ebinto",
                            Price = 300m,
                            Stock = 45
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Soleil des Independances",
                            Price = 500m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Les Crapeaux Brousses",
                            Price = 550m,
                            Stock = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
